### ISSUE TITLE
Test are failing with ruby-kafka 0.5.0

### ISSUE THREAD

**Issue by TommyGustafsson** [klarna/phobos#48]
The release of ruby-kafka 0.5.0 is not working with Phobos. Listener tests are breaking with

```shell
 IOError:
  stream closed
./vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.5.0/lib/kafka/socket_with_timeout.rb:79:in `write'
./vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.5.0/lib/kafka/socket_with_timeout.rb:79:in `write'
./vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.5.0/lib/kafka/protocol/encoder.rb:23:in `write'
./vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.5.0/lib/kafka/protocol/encoder.rb:49:in `write_int32'
```

**Comment by klippx** [comment]
@jasondoc3 Continuing the discussion about pinning: I think pinning is not a solution, but a workaround. I think it is important for us to only ship Phobos with releases of RubyKafka we know are working, and since we know (by chance) that the test suite is now broken, we don't want Phobos users that run `bundle update` to update all gems to get their Phobos projects broken.

After performing this "hotfix" we need to find what the real issue is.

**Comment by jasondoc3** [comment]
@klippx Thanks for the explanation. Once I saw this issue I figured that was the case 👍
