### ISSUE TITLE
Consumer not able to commit offsets for some partitions

### ISSUE THREAD

**Issue by mehdimu** [klarna/phobos#67]
So we are trying to debug this issue where the consumer is not able to commit offsets for certain partitions and it starts reading again from the same offset. This goes into infinite reading.

So in the phobos log, this is what we see:
```
[2018-01-26T21:20:14:846+0000Z] INFO -- Phobos : <Hash> {:message=>"Committed offset", :batch_size=>1133, :partition=>1, :offset_lag=>567, :highwater_mark_offset=>2853, :listener_id=>"e8398e", :group_id=>"events_group", :topic=>"events", :time_elapsed=>968.744}

[2018-01-26T21:20:14:846+0000Z] INFO -- RubyKafka : Committing offsets: events/1:2286

[2018-01-26T21:20:14:846+0000Z] WARN -- RubyKafka : Connection has been unused for too long, re-connecting...

[2018-01-26T21:20:14:884+0000Z] ERROR -- RubyKafka : Error committing offsets: Kafka::UnknownMemberId

[2018-01-26T21:20:14:885+0000Z] INFO -- RubyKafka : Joining group `events_group`

[2018-01-26T21:20:14:886+0000Z] ERROR -- RubyKafka : Failed to join group; resetting member id and retrying in 1s...
```

Any suggestions or ideas would help? Please and thank you!

FYI, phobos config:
```
consumer:
  # number of seconds after which, if a client hasn't contacted the Kafka cluster,
  # it will be kicked out of the group
  session_timeout: 300
  # interval between offset commits, in seconds
  offset_commit_interval: 10
  # number of messages that can be processed before their offsets are committed.
  # If zero, offset commits are not triggered by message processing
  offset_commit_threshold: 0
  # interval between heartbeats; must be less than the session window
  heartbeat_interval: 10

backoff:
  min_ms: 1000
  max_ms: 60000
```

**Comment by klippx** [comment]
We recognize this as a FAQ / common kafka configuration problem. 

A likely scenario is that the consumer is taking to long time to process a batch, causing the kafka broker to disconnect the consumer. When the consumer then tries to commit, the broker no longer recognizes them.

Checklist:
- Do you know how long time it takes to for your consumer to consume a single message?
- Do you know how long time it takes to for your consumer to consume a batch? 
- Do you know the message size?
- Do you know the batch size and the amount of messages?

Having answers to this will help you configure phobos and ruby-kafka but it is not a requirement. But I can answer some questions by looking at your log:
- Batch size is 1133 messages
- Duration taken is 968.744 seconds
- This gives about 0.86 messages/second for this sample. This varies a lot over time.
- But 968 seconds to consume the batch is way beyond the session timeout of 300seconds.

Hence, I suspect batch size is too large compared to the amount of time it takes to consume it. 

When this happens, we usually tweak the `max_bytes_per_partition` in the `listener` config section. The ruby-kafka default is 1048576 (1MB). I would turn this down by for this handler in order to get smaller batches to consume. Since I have no good idea about what kind of sample 966 seconds is (fast outlier or slow outlier) I will be a bit conservative in my suggestion. Let's say we want to get batch consumption down to about 1 minute instead of around 16 minutes, so it seems lowering 1MB by factor 16 could be a good idea. 1024/16 = 64, so 

```yml
    # maximum amount of data fetched from a single partition at a time, default is 1024 * 1024
    max_bytes_per_partition: <%= 16 * 1024 %>
```

**NB** Please be aware that changing parameters without measuring before/after might be a treacherous path. I would suggest looking into monitoring of your consumer as soon as possible after this issue is resolved. We have had great success with prometheus, such that we even built phobos specific tooling for it: https://github.com/phobos/phobos_prometheus

As soon as we change any configuration we can immediately see what kind of effect it has (positive or negative) on our grafana monitoring for the consumers. It is a lot more scientific and it gives us such a peace of mind to feel in control of what is going on. Parsing logs by hand is not very fun.

Maybe prometheus isn't an option for you, but the same approach can be used for other tools such as graphite.

**Comment by dorner** [comment]
On the same team as @mehdimu here. :)

@klippx we were using Phobos 1.4.1 which did not support batch processing. We've moved over to single message processing for the topics which we think might yield slow messages. It might be a bit slower, but using RubyKafka's offset_commit_interval, we should at least be protected from the issue where we simply cannot continue (and our queue is stuck forever) just because we're taking too long to process a batch. Is that a reasonable solution?

**Comment by jasondoc3** [comment]
@dorner @mehdimuv The default behavior for phobos is to process messages in batches. If you have a lot of messages that are small in size, but each take almost a second to process you will most likely exceed the `session_timeout` for the kafka consumer. When processing messages in batches, `ruby-kafka` does not try to send a heartbeat to the kafka broker or commit offsets until _the entire batch is processed_. If the time to process the batch takes longer than the session timeout, the consumer will fail to send a heartbeat to kafka in time. Kafka will kick the consumer out of the group (hence the `Kafka::UnknownMemberId` error) and offsets will fail to commit. If you set the `delivery` option for the listener to `message`, ruby-kafka will check if needs to commit offsets / send heartbearts after "each message" vs "each batch." How often it sends heartbeats / commits offsets will depend on the settings in your phobos config. This might be the better option for you if each message takes awhile to process. See the conversations in https://github.com/klarna/phobos/pull/42 for more details. @klippx I know I mentioned potentially making `each_message` the default behavior at some point in the future. Do you have anymore thoughts on this?

What @klippx says about changing the `max_bytes_per_partition` setting is correct. However, be careful in tweaking this setting. If there is a message in a partition that is larger in bytes than the `max_bytes_per_partition` setting (and kafka allows a message size this large), `ruby-kafka` won't be able to fetch the entire message. Processing on that partition will stall.

**Comment by klippx** [comment]
@dorner @mehdimu Any updates on this issue, were you able to get it working?

@jasondoc3 I don't know if it would be strictly better to change the default. Maybe we should compile a living document with compelling pros and cons we can live with, or discuss it more in the Discord chat :)

**Comment by dorner** [comment]
@klippx yep, it appears that switching from `batch` to `message` solved the problem. We were wondering why the consumer settings like `offset_commit_interval` weren't working :) At the very least, the default `phobos.yml` should indicate in the comments that those settings will only work in message mode and not batch mode.

**Comment by jasondoc3** [comment]
@dorner Those settings do work in batch mode.

However, `ruby-kafka` only checks to send heartbeats / commit offsets after the entire batch has been processed. In other words, sending heartbeats and committing offsets are done in the same thread as the processing itself. If your batches take 5 seconds to process and your `offset_commit_interval` is 20 seconds, offsets are committed after the 4th batch is successfully processed. If your batches take 20 seconds to process and your `offset_commit_interval` is 5 seconds, offsets are committed after every batch.

See the source code here: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L283

**Comment by jasondoc3** [comment]
@klippx I'd be happy to create a document or discuss :)

**Comment by klippx** [comment]
@jasondoc3 you are welcome to join the discord chat and we can discuss next steps there
